const OrderConstants = {
    CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
    CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",

    MY_ORDER_REQUEST: "MY_ORDER_REQUEST",
    MY_ORDER_SUCCESS: "MY_ORDER_SUCCESS",
    MY_ORDER_FAIL: "MY_ORDER_FAIL",

    ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
    ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
    ORDER_DETAILS_FAIL: "ORDER_DETAILS_FAIL",

    // For admin
    ALL_ORDERS_REQUEST: "ALL_ORDERS_REQUEST",
    ALL_ORDERS_SUCCESS: "ALL_ORDERS_SUCCESS",
    ALL_ORDERS_FAIL: "ALL_ORDERS_FAIL",

    UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
    UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
    UPDATE_ORDER_FAIL: "UPDATE_ORDER_FAIL",
    UPDATE_ORDER_RESET: "UPDATE_ORDER_RESET",

    DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
    DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
    DELETE_ORDER_FAIL: "DELETE_ORDER_FAIL",
    DELETE_ORDER_RESET: "DELETE_ORDER_RESET",

    CLEAR_ERRORS: "CLEAR_ERRORS"
}

export default OrderConstants;